### PR TITLE
Fall back to xml module in case lxml module is not installed

### PR DESCRIPTION
**Pull request by uphoffc**

### CODE REVIEW

**Comment by Thomas-Ulrich** [comment]
What about:
```
pip download lxml
pip install --user lxml-4.6.3-cp37-cp37m-manylinux2014_x86_64.whl
```
or just `pip install lxml`?

**Comment by uphoffc** [comment]
Yes its not difficult, but on ng it is annoying (any hints how to streamline pip on ng?). lxml.etree is meant to be drop-in replacement for xml.etree.ElementTree, i.e. the latter offers the same functionality but might be a bit slower (which doesn't really hurt here as the xdmf files are pretty small).

**Comment by Thomas-Ulrich** [comment]
I don't know what you mean with "streamline pip".
The first command is what I would use.
(after updating pip with something like
```
pip download pip==20.1
pip install  --user pip-20.1-py2.py3-none-any.whl
```
)
Why not then totally replacing lxml.etree by xml.etree.ElementTree?
I don't care if it slightly slower.

**Comment by krenzland** [comment]
You can use pip on supermuc-ng:
https://doku.lrz.de/display/PUBLIC/FAQ%3A+Python+and+R+on+SuperMUC-NG+by+using+conda
Follow method 2. Pip can also use the proxy

**Pull request merged**
